swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /article:
    get:
      operationId: article.read_all
      tags:
        - Article
      summary: Read the entire list of article
      description: Read the list of article
      responses:
        200:
          description: Successfully read article list operation
          schema:
            type: array
            items:
              properties:
                pmid:
                  type: string
                pmcid:
                  type: string
                title:
                  type: string
                content_abstract:
                  type: string
                content_full:
                  type: string
                authors:
                  type: array
                  items:
                    type: string
                date_pub:
                  type: string
                journal_pub:
                  type: string

  /generate:
    post:
      operationId: article.generate
      tags:
        - Article
      summary: Fetch the article for the application
      description: Fetch the article for the application
      responses:
        200:
          description: Successfully fetched the articles

  /recommendations/{pmid}:
    get:
      operationId: article.recommendations
      tags:
        - Article
      summary: Fetch the recommendations of articles for a specific article
      description: Fetch the recommendations of articles for a specific article
      parameters:
        - name: pmid
          in: path
          description: Pmid of the article for the recommendations
          type: integer
          required: True
      responses:
        200:
          description: Successfully fetched the recommendations
          schema:
            properties:
                recommendations:
                  type: object
                  properties:
                    top_words:
                      type: array
                      items:
                        type: object
                        properties:
                          place:
                            type: integer
                          word:
                            type: string


  /article/{pmid}:
    get:
      operationId: article.read_one
      tags:
        - Article
      summary: Read one article from the article list
      description: Read one article from the article list
      parameters:
        - name: pmid
          in: path
          description: Pmid of the article to get from the list
          type: integer
          required: True
      responses:
        200:
          description: Successfully read article from article list operation
          schema:
            properties:
              pmid:
                type: string
              pmcid:
                type: string
              title:
                type: string
              content_abstract:
                type: string
              content_full:
                type: string
              date_pub:
                type: string
              journal_pub:
                type: string
              authors:
                type: array
                items:
                  type: string
              recommendations:
                type: object
                properties:
                  top_words:
                    type: array
                    items:
                      type: object
                      properties:
                        place:
                          type: integer
                        word:
                          type: string
                  articles:
                    type: array
                    items:
                      type: integer

  /generateDLA:
    post:
      operationId: generateLDA.generate
      tags:
        - LDA
      summary: Generate the LDA model for the futur recommendations
      description: Generate the LDA model for the futur recommendations
      responses:
        200:
          description: Successfully generate the LDA model
